/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package room;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sistem.informasi.hotel.dan.restaurant.koneksi;

/**
 *
 * @author ASUS
 */
public class master_room extends javax.swing.JPanel {
    public DefaultTableModel model_tabel;
    koneksi kn = new koneksi();
    
    public master_room() {
        initComponents();
        
        model_tabel = new DefaultTableModel();
        tbl_roomDetail.setModel(model_tabel);
        
        model_tabel.addColumn("ID");
        model_tabel.addColumn("Jenis");
        model_tabel.addColumn("Harga");
        model_tabel.addColumn("Status");
        
        setDataToTabel();
    }
    
    public void setDataToTabel(){
        model_tabel.getDataVector().removeAllElements();
        model_tabel.fireTableDataChanged();
        ResultSet data = null;
        
        String query ="SELECT* FROM tb_room";
        
        try{
            data = kn.getStatement().executeQuery(query);
            while(data.next()){
                Object[] o = new Object[4];
                o[0] = data.getString("id_room");
                o[1] = data.getString("jenis_kamar");
                o[2] = data.getString("harga");
                o[3] = data.getString("status");
                
                model_tabel.addRow(o);
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Data gagal di load");
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group_rd = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_roomDetail = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        tf_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_jenis = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_harga = new javax.swing.JTextField();
        btn_kosongkan = new javax.swing.JButton();
        btn_tambah = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        rd_ready = new javax.swing.JRadioButton();
        rd_booked = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_roomDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_roomDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_roomDetailMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_roomDetail);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 760, 210));

        jLabel1.setText("ID Room");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 242, 760, 10));

        jLabel2.setText("Jenis");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, -1, -1));

        tf_id.setEditable(false);
        add(tf_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 140, 30));

        jLabel3.setText("Harga");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, -1, -1));
        add(tf_jenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 140, 30));

        jLabel4.setText("Status");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, -1, -1));
        add(tf_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 140, 30));

        btn_kosongkan.setText("Kosongkan");
        btn_kosongkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kosongkanActionPerformed(evt);
            }
        });
        add(btn_kosongkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, 100, 30));

        btn_tambah.setText("Tambah");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });
        add(btn_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 100, 30));

        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, 100, 30));

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 100, 30));

        group_rd.add(rd_ready);
        rd_ready.setText("Ready");
        add(rd_ready, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, -1, -1));

        group_rd.add(rd_booked);
        rd_booked.setText("Booked");
        add(rd_booked, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kosongkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kosongkanActionPerformed
        // TODO add your handling code here:
        tf_id.setText("");
        tf_jenis.setText("");
        tf_harga.setText("");
        group_rd.clearSelection();
        
    }//GEN-LAST:event_btn_kosongkanActionPerformed

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        // TODO add your handling code here:
        String jenis = tf_jenis.getText().toString();
        String harga = tf_harga.getText().toString();
        String status = "";
        
        if(rd_ready.isSelected()){
            rd_ready.setSelected(true);
            rd_booked.setSelected(false);
            status = rd_ready.getText().toString();
        }else if(rd_booked.isSelected()){
            rd_ready.setSelected(false);
            rd_booked.setSelected(true);
            status = rd_booked.getText().toString();
        }
        
        String query = "INSERT INTO tb_room (jenis_kamar, harga, status) VALUES ('"
                + jenis+"',"+harga+",'"+status+"')";
        
        try{
            kn.getStatement().executeUpdate(query);
            JOptionPane.showMessageDialog(this, "Data berhasil Ditambahkan");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Data gagal ditambahkan");
        }
        setDataToTabel();
        
       tf_id.setText("");
        tf_jenis.setText("");
        tf_harga.setText("");
        group_rd.clearSelection();
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        String id = tf_id.getText().toString();
        String jenis = tf_jenis.getText().toString();
        String harga = tf_harga.getText().toString();
        String status = "";
        
        if(rd_ready.isSelected()){
            rd_ready.setSelected(true);
            rd_booked.setSelected(false);
            status = rd_ready.getText().toString();
        }else if(rd_booked.isSelected()){
            rd_ready.setSelected(false);
            rd_booked.setSelected(true);
            status = rd_booked.getText().toString();
        }
        
        System.out.println(id);
        System.out.println(jenis);
        System.out.println(harga);
        System.out.println(status);
        
        String query = "UPDATE tb_room SET jenis_kamar= \""+jenis+"\", harga= "+harga+ ", status = \""+status+"\" "
                + "WHERE id_room = "+id;
        
        try{
            kn.getStatement().executeUpdate(query);
            JOptionPane.showMessageDialog(this, "Edit Data Berhasil");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Edit Data Gagal");
        }
        setDataToTabel();
        
        tf_id.setText("");
        tf_jenis.setText("");
        tf_harga.setText("");
        group_rd.clearSelection();
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        String id = tf_id.getText().toString();
        String query = "DELETE FROM tb_room WHERE id_room = "+id;
        
        int i = JOptionPane.showConfirmDialog(this, "Apakah anda yakin ingin menghapus data ?");
        if(i==0){
            try{
                kn.getStatement().executeUpdate(query);
                JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Data Gagal Dihapus");
            }
        }
        setDataToTabel();
        
        tf_id.setText("");
        tf_jenis.setText("");
        tf_harga.setText("");
        group_rd.clearSelection();        
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void tbl_roomDetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_roomDetailMouseClicked
        // TODO add your handling code here:
        String id = tbl_roomDetail.getValueAt(tbl_roomDetail.getSelectedRow(), 0).toString();
        String jenis = tbl_roomDetail.getValueAt(tbl_roomDetail.getSelectedRow(), 1).toString();
        String harga = tbl_roomDetail.getValueAt(tbl_roomDetail.getSelectedRow(), 2).toString();
        String status = tbl_roomDetail.getValueAt(tbl_roomDetail.getSelectedRow(), 3).toString();
        
        tf_id.setText(id);
        tf_jenis.setText(jenis);
        tf_harga.setText(harga);
        
        if(status.equals("Ready")){
            rd_ready.setSelected(true);
            rd_booked.setSelected(false);
        }else if(status.equals("Booked")){
            rd_ready.setSelected(false);
            rd_booked.setSelected(true);
        }
    }//GEN-LAST:event_tbl_roomDetailMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_kosongkan;
    private javax.swing.JButton btn_tambah;
    private javax.swing.ButtonGroup group_rd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rd_booked;
    private javax.swing.JRadioButton rd_ready;
    private javax.swing.JTable tbl_roomDetail;
    private javax.swing.JTextField tf_harga;
    private javax.swing.JTextField tf_id;
    private javax.swing.JTextField tf_jenis;
    // End of variables declaration//GEN-END:variables
}
