/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurant;

import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sistem.informasi.hotel.dan.restaurant.koneksi;

/**
 *
 * @author ASUS
 */
public class laporan_penjualan extends javax.swing.JPanel {
    public DefaultTableModel model_tabel;
    koneksi kn = new koneksi();
    public int total_nasgor, total_miegor, total_esTeh, total_esJeruk;
    String date_from, date_until;
    
    public laporan_penjualan() {
        initComponents();
        
        model_tabel = new DefaultTableModel();
        tbl_laporanPenjualan.setModel(model_tabel);
        
        model_tabel.addColumn("ID_Penjualan");
        model_tabel.addColumn("Tanggal");
        model_tabel.addColumn("Nasi Goreng");
        model_tabel.addColumn("Mie Goreng");
        model_tabel.addColumn("Es Teh");
        model_tabel.addColumn("Es Jeruk");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_laporanPenjualan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        tgl_from = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        tgl_until = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_totalEsTeh = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_totalNasgor = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbl_totalMiegor = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbl_totalEsJeruk = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_laporanPenjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_laporanPenjualan);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 720, 180));

        jLabel1.setText("Sampai Tanggal");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, 30));

        tgl_from.setDateFormatString("yyyy-MM-dd");
        add(tgl_from, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 150, 30));

        jLabel2.setText("Dari Tanggal");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, 30));

        tgl_until.setDateFormatString("yyyy-MM-dd");
        add(tgl_until, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 140, 30));

        jButton1.setText("PROSES");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 43, -1, 30));

        jPanel1.setBackground(new java.awt.Color(225, 112, 85));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ES TEH");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Total :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        lbl_totalEsTeh.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl_totalEsTeh.setForeground(new java.awt.Color(255, 255, 255));
        lbl_totalEsTeh.setText("0");
        jPanel1.add(lbl_totalEsTeh, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 80, 40));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 140, 80));

        jPanel2.setBackground(new java.awt.Color(9, 132, 227));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NASI GORENG");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Total :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        lbl_totalNasgor.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl_totalNasgor.setForeground(new java.awt.Color(255, 255, 255));
        lbl_totalNasgor.setText("0");
        jPanel2.add(lbl_totalNasgor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 80, 40));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 140, 80));

        jPanel3.setBackground(new java.awt.Color(253, 203, 110));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("MIE GORENG");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Total :");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        lbl_totalMiegor.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl_totalMiegor.setForeground(new java.awt.Color(255, 255, 255));
        lbl_totalMiegor.setText("0");
        jPanel3.add(lbl_totalMiegor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 80, 40));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 140, 80));

        jPanel4.setBackground(new java.awt.Color(99, 110, 114));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ES JERUK");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Total :");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        lbl_totalEsJeruk.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl_totalEsJeruk.setForeground(new java.awt.Color(255, 255, 255));
        lbl_totalEsJeruk.setText("0");
        jPanel4.add(lbl_totalEsJeruk, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 80, 40));

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 140, 80));

        jButton2.setText("Detail Peggunaan Bahan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       model_tabel.getDataVector().removeAllElements();
       model_tabel.fireTableDataChanged();
       String formatTgl = "yyyy-MM-dd";
       SimpleDateFormat format_date = new SimpleDateFormat(formatTgl);
       
       date_from = String.valueOf(format_date.format(tgl_from.getDate()));
       date_until = String.valueOf(format_date.format(tgl_until.getDate()));
       
       String query = "SELECT * FROM tb_penjualan WHERE tanggal BETWEEN '"+date_from+"' and '"+date_until+"'";
       String query_total_nasgor = "SELECT SUM(nasi_goreng) as \"Total\" FROM tb_penjualan "
               + "WHERE tanggal BETWEEN '"+date_from+"' AND '"+date_until+"'";
       
       String query_total_miegor = "SELECT SUM(mie_goreng) as \"Total\" FROM tb_penjualan "
               + "WHERE tanggal BETWEEN '"+date_from+"' AND '"+date_until+"'";
       
       String query_total_esTeh = "SELECT SUM(es_teh) as \"Total\" FROM tb_penjualan "
               + "WHERE tanggal BETWEEN '"+date_from+"' AND '"+date_until+"'";
       
       String query_total_esJeruk = "SELECT SUM(es_jeruk) as \"Total\" FROM tb_penjualan "
               + "WHERE tanggal BETWEEN '"+date_from+"' AND '"+date_until+"'";
       ResultSet data = null;
       ResultSet total = null;
       try{
           data = kn.getStatement().executeQuery(query);
           while(data.next()){
               Object[] o = new Object[6];
               o[0] = data.getString("id_penjualan");
               o[1] = data.getString("tanggal");
               o[2] = data.getString("nasi_goreng");
               o[3] = data.getString("mie_goreng");
               o[4] = data.getString("es_teh");
               o[5] = data.getString("es_jeruk");
               
               model_tabel.addRow(o);
           }
           total = kn.getStatement().executeQuery(query_total_nasgor);
           if(total.next()){
              total_nasgor = Integer.parseInt(total.getString("Total"));
               lbl_totalNasgor.setText(total.getString("Total"));
           }
           
           total = kn.getStatement().executeQuery(query_total_miegor);
           if(total.next()){
               total_miegor = Integer.parseInt(total.getString("Total"));
               lbl_totalMiegor.setText(total.getString("Total"));
           }
           
           total = kn.getStatement().executeQuery(query_total_esTeh);
           if(total.next()){
               total_esTeh = Integer.parseInt(total.getString("Total"));
               lbl_totalEsTeh.setText(total.getString("Total"));
           }
           
           total = kn.getStatement().executeQuery(query_total_esJeruk);
           if(total.next()){
               total_esJeruk = Integer.parseInt(total.getString("Total"));
               lbl_totalEsJeruk.setText(total.getString("Total"));
           }
           
       }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Data gagal di load");
            
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        laporan_penggunaan_bahan lpb = new laporan_penggunaan_bahan();
        lpb.setTgl(date_from, date_until);
        lpb.setTotalBahanNasgor(total_nasgor);
        lpb.setTotalBahanMiegor(total_miegor);
        lpb.setTotalBahanEsTeh(total_esTeh);
        lpb.setTotalBahanEsJeuk(total_esJeruk);
        lpb.setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_totalEsJeruk;
    private javax.swing.JLabel lbl_totalEsTeh;
    private javax.swing.JLabel lbl_totalMiegor;
    private javax.swing.JLabel lbl_totalNasgor;
    private javax.swing.JTable tbl_laporanPenjualan;
    private com.toedter.calendar.JDateChooser tgl_from;
    private com.toedter.calendar.JDateChooser tgl_until;
    // End of variables declaration//GEN-END:variables
}
